### PR TITLE
build: distribute two components

### PR DESCRIPTION
**Pull request by ChristianMurphy**
`<equella-image-carousel>` and `<equella-search-results>` are included in the *equella.js* bundle

### CODE REVIEW

**Comment by drewwills** [comment]
@ChristianMurphy --

It's almost working.

In uPortal I have the following...

```
<script src="https://unpkg.com/vue@2.5.16"></script>
<script type="text/javascript" src="/uPortal/equella.js"></script>
<equella-search-results msg="Equella Searching Demo" searchResultTypes="mini courses" baseUrl="https://equella.unicon.net/demo-oa18-up-eq-integ" collectionId="1ffa9507-4313-4f4f-9f6c-b923a897c515" resultIcon="_THUMBS/promo.jpeg_PREVIEW_.jpeg" resultLandingPage="index.html"/>
```
The component is trying to run, but doesn't seem to be reading the properties (attributes on the custom element) correctly.

**Comment by ChristianMurphy** [comment]
@drewwills anything printed to the browser's developer console?

**Comment by drewwills** [comment]
@ChristianMurphy 

console

The script thinks `baseUrl` is undefined, so it tries to fetch '/api/search/?start=0&length=10&collections=...' as a relative URL (on the uPoirtal server).

**Comment by ChristianMurphy** [comment]
use kebab case for attributes when leveraging the web component
```html
<script src="https://unpkg.com/vue@2.5.16"></script>
<script type="text/javascript" src="/uPortal/equella.js"></script>
<equella-search-results msg="Equella Searching Demo" search-result-types="mini courses" base-url="https://equella.unicon.net/demo-oa18-up-eq-integ" collection-id="1ffa9507-4313-4f4f-9f6c-b923a897c515" result-icon="_THUMBS/promo.jpeg_PREVIEW_.jpeg" result-landing-page="index.html"/>
```

**Comment by drewwills** [comment]
It works!  (But it's awfully hard to guess.)

**Pull request merged**
